-- ============================================================
-- NATIONS / TECH TREES
-- ============================================================

create table public.nations (
    id text primary key,
    name text not null
);


-- ============================================================
-- OPERATORS
-- ============================================================

create table public.operators (
    id text primary key,
    name text not null
);


-- ============================================================
-- VEHICLE TYPES
-- ============================================================

create table public.vehicle_types (
    id public.vehicle_type_id primary key,
    name text not null
);


-- ============================================================
-- VEHICLE STATUSES
-- ============================================================

create table public.vehicle_statuses (
    id public.vehicle_status_id primary key,
    name text not null
);


-- ============================================================
-- VEHICLE CLASSES
-- ============================================================

create table public.vehicle_classes (
    id public.vehicle_class_id primary key,
    name text not null
);


-- ============================================================
-- VEHICLES
-- ============================================================

create table public.vehicles (
    id text primary key,

    name text not null,

    vehicle_type_id public.vehicle_type_id not null,
    nation_id text not null,
    operator_id text,
    status_id public.vehicle_status_id not null,
    class_id public.vehicle_class_id not null,

    rank smallint not null,

    battle_rating_ab numeric(3,1) not null,
    battle_rating_rb numeric(3,1) not null,
    battle_rating_sb numeric(3,1) not null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint vehicles_rank_check
      check (rank between 1 and 9),
    
    constraint vehicles_br_ab_check
      check (battle_rating_ab between 1.0 and 14.7),

    constraint vehicles_br_rb_check
      check (battle_rating_rb between 1.0 and 14.7),

    constraint vehicles_br_sb_check
      check (battle_rating_sb between 1.0 and 14.7)
);


-- ============================================================
-- WEAPONS
-- ============================================================

create table public.weapons (
    id text primary key,

    name text not null,

    weapon_type text,

    caliber_mm numeric,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- AMMUNITION
-- ============================================================

create table public.ammunition (
    id text primary key,

    designation text not null,

    category public.shell_category,
    family public.shell_family,
    variant public.shell_variant,

    damage_type public.damage_type,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================================
-- VEHICLE WEAPONS
--
-- A vehicle can have multiple weapon installations.
--
-- Example:
--
-- Leopard 2PL
--   #1 = 120 mm cannon
--   #3 = coaxial MG3
--   #4 = normal MG3
-- ============================================================

create table public.vehicle_weapons (
    id bigint generated by default as identity primary key,

    vehicle_id text not null,
    weapon_id text not null,

    type text,
    quantity integer not null default 1,
    slot text -- weapon placement: main, coaxial, roof
);


-- ============================================================
-- WEAPON AMMUNITION
--
-- Ammunition supported by a generic weapon.
--
-- Example:
--
-- Rh120 L/44
--   -> DM53
--   -> DM11
--   -> etc.
-- ============================================================

create table public.weapon_ammunition (
    id bigint generated by default as identity primary key,

    weapon_id text not null,
    ammunition_id text not null,

    position integer,

    is_default boolean not null default false,

    max_quantity integer
);


-- ============================================================
-- VEHICLE AMMUNITION
--
-- Vehicle-specific ammunition statistics.
--
-- This is where things like:
--
-- DM53 on Leopard 2A5 = 560 mm
-- DM53 on Leopard 2A7 = 620 mm
--
-- can be stored separately.
-- ============================================================

create table public.vehicle_ammunition (
    id bigint generated by default as identity primary key,

    vehicle_id text not null,
    ammunition_id text not null,

    armor_type text,
    damage_type text,

    caliber_mm numeric,
    projectile_mass_kg numeric,
    penetration_mm numeric,
    muzzle_velocity_ms numeric,

    reload_time_seconds numeric,

    notes text
);


-- ============================================================
-- BELTS
--
-- Reusable belt definitions.
--
-- Example:
--
-- germ_leopard_2pl_default_mg_belt
-- name = Default
-- belt_filling = AP/T
-- max_penetration_mm = 13
-- ============================================================

create table public.belts (
    id text primary key,

    name text not null,

    belt_filling text,

    max_penetration_mm numeric,

    description text
);


-- ============================================================
-- BELT AMMUNITION
--
-- Ordered ammunition inside a belt.
--
-- Example:
--
-- position 1 = AP
-- position 2 = T
-- position 3 = AP
-- position 4 = T
-- ============================================================

create table public.belt_ammunition (
    id bigint generated by default as identity primary key,

    belt_id text not null,
    ammunition_id text not null,

    position integer not null,

    quantity integer not null default 1
);


-- ============================================================
-- VEHICLE BELTS
--
-- Assigns a reusable belt to a specific weapon installation
-- on a specific vehicle.
--
-- This allows:
--
-- Leopard 2PL MG3       -> same belt
-- Leopard 2PL coax MG3  -> same belt
-- ============================================================

create table public.vehicle_belts (
    id bigint generated by default as identity primary key,

    vehicle_id text not null,
    vehicle_weapon_id bigint not null,
    belt_id text not null,

    is_default boolean not null default false,

    created_at timestamptz not null default now()
);


-- ============================================================
-- LIKED VEHICLES
--
-- Saves liked vehicles of users.
-- ============================================================

create table public.vehicle_likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  vehicle_id text not null references public.vehicles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, vehicle_id)
);

alter table public.vehicle_likes enable row level security;

create policy "Users can read their own likes"
on public.vehicle_likes for select to authenticated
using (user_id = (select auth.uid()));

create policy "Users can like vehicles"
on public.vehicle_likes for insert to authenticated
with check (user_id = (select auth.uid()));

create policy "Users can unlike vehicles"
on public.vehicle_likes for delete to authenticated
using (user_id = (select auth.uid()));